#########################################
# From-Query Pipeline Config Parameters #
#########################################

# Config parameters in this file are used as defaults by the
# From-Query version of the pipeline (Snakefile).
# To override the defaults, we recommend creating a copy of this file
# and passing your new file to Snakemake using the --configfile flag.
# Any parameters in the new config file will overwrite the defaults
# listed here.

###########
# File IO #
###########

# Specify the input and output directories
# Usually, we place the output directory inside the input directory
input_dir: "input/"
output_dir: "input/output/"

# Provide a name for the analysis, which is set as a prefix for key output files
analysis_name: "example"

#####################
# Foldseek settings #
#####################

# Choose which Foldseek databases to query
# To avoid overloading the Foldseek server, we recommend limiting your search
# to only the databases relevant to your query.
foldseek_databases:
- "afdb50"
- "afdb-swissprot"
- "afdb-proteome"

##################
# BLAST settings #
##################

# Set maximum number of BLAST hits to retrieve
max_blasthits: 3000
# The blast word size: the length of exact matches to start the candidate alignments.
blast_word_size: 5
# The maximal e-value to use for the blast search.
blast_evalue: 1.0
# The blast_word_size to use, if attempts with blast_word_size have failed.
blast_word_size_backoff: 6
# The number of attempts to use blast_word_size, before backing off to blast_word_size_backoff.
blast_word_size_attempts_before_backoff: 1

######################
# Structure settings #
######################

# Set maximum number of total structures to download (combined BLAST + Foldseek hits)
# By default, we prioritize downloading structures from Foldseek
max_structures: 5000

# Specify the maximum and minimum length of proteins to filter by
# prior to downloading structures from AlphaFold.
# Setting min_length to 0 removes lower bound filtering.
# Setting max_length to 0 removes upper bound filtering.
# min_length must be less than max_length.
min_length: 0
max_length: 0

# Specify whether or not to override protein quality checks prior to download
# from UniProt. By default the pipeline removes proteins marked as fragments
# by UniProt, as well as proteins that have been deleted from UniProt.
override_quality_check: False

#####################
# Features settings #
#####################

# Specify any additional metadata fields to download from UniProt
uniprot_additional_fields: []

# For user-provided proteins, you can pass a file through this parameter
# that contains protein metadata similar to that which would be pulled
# from UniProt. See the README.md for an explanation of the expected columns.
# If this file doesn't exist, this parameter is ignored.
override_file: "features_override.tsv"

#####################
# Plotting settings #
#####################

# Choose which plotting modes to use
# Default is "pca_tsne" and "pca_umap"
# Also accepts "pca", "tsne", and "umap"
plotting_modes:
- "pca_tsne"
- "pca_umap"

# Set the broad taxonomic groups that will be categorized in plots
# Also accepts 'bac' which displays some large bacterial taxonomic groups.
# See README.md for more details
taxon_focus: 'euk'
