input_dir: "input/"
output_dir: "output_testing/"
analysis_prefix: "testing"

query_mode: "remote"

foldseek_databases:
- "afdb50"
- "afdb-swissprot"
- "afdb-proteome"
plotting_modes:
- "pca_tsne"
- "pca_umap"

max_blasthits: 3000
max_structures: 5000
