from setuptools import setup

setup(
    name="ProteinCartography",
    url="https://github.com/Arcadia-Science/ProteinCartography-private",
    author="Dennis Sun",
    author_email="dennis.sun@arcadiascience.com",
    packages=["ProteinCartography"],
    version="0.0.2",
    license="MIT",
    description="Builds maps of protein space from structures.",
    scripts=[
        "ProteinCartography/aggregate_features.py",
        "ProteinCartography/aggregate_hits.py",
        "ProteinCartography/dim_reduction.py",
        "ProteinCartography/esmfold_apiquery.py",
        "ProteinCartography/extract_blast_hits.py",
        "ProteinCartography/extract_foldseek_hits.py",
        "ProteinCartography/extract_input_protein_distances.py",
        "ProteinCartography/fetch_accession.py",
        "ProteinCartography/foldseek_apiquery.py",
        "ProteinCartography/foldseek_clustering.py",
        "ProteinCartography/get_source_of_hits.py",
        "ProteinCartography/leiden_clustering.py",
        "ProteinCartography/map_refseq_ids.py",
        "ProteinCartography/plot_interactive.py",
        "ProteinCartography/fetch_uniprot_metadata.py",
        "ProteinCartography/rescue_mapping.py",
    ],
)
