name: Bug report
description: Report something that is broken or incorrect
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: command_used
    attributes:
      label: Command used and terminal output
      description: Steps to reproduce the behaviour. Please paste the command you used
        to launch the pipeline and the output from your terminal.
      render: console
      placeholder: "$ snakemake --snakefile Snakefile ...


        Some output where something broke

        "
  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: "Please drag and drop the relevant files here. Create a `.zip` archive
        if the extension is not allowed.

        Your verbose log `<hash>.snakemake.log` file is often useful _(this is a hidden file
        in the directory where you launched the pipeline)_ as well as custom 
        Snakemake configuration files.

        You can find the log file in the `.snakemake/log/` directory.
        The logs are generated with a timestamp for each time you execute the `snakemake` command.

        "
  - type: textarea
    id: system
    attributes:
      label: System information
      description: "* Snakemake version _(eg. 21.10.3)_

        * Hardware _(eg. HPC, Desktop, Cloud)_

        * Executor _(eg. slurm, local, awsbatch)_

        * OS _(eg. CentOS Linux, macOS, Linux Mint)_

        * Version of Arcadia-Science/ProteinCartography _(eg. 0.4, 0.4.1)_

        "
