input_dir: "demo/"
output_dir: "demo/output/"
analysis_name: "actin-small"

plotting_modes:
- "pca_umap"

max_blasthits: 10
max_foldseekhits: 10
max_structures: 10

# Resource execution settings
resources:
    mem_mb: 16 * 1000

cores: 8
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 10
