#!/usr/bin/env python
"""Run BLAST for a ProteinCartography search-mode seed.

``blast_utils`` defaults to NCBI's WWW/QBlast URL API (``PC_BLAST_BACKEND=www``)
and writes the same tabular TSV ProteinCartography expects. Soft-fail
(``PC_BLAST_SOFT_FAIL=1``) lets Foldseek-only maps complete if NCBI is down;
set ``0`` for hard failure. Legacy ``blastp -remote`` remains available via
``PC_BLAST_BACKEND=remote``.
"""

from __future__ import annotations
import argparse
import os
import sys
from pathlib import Path

import blast_utils
import constants

# If necessary, mock ``run_blast`` (see ``tests.mocks``).
if os.environ.get("PROTEINCARTOGRAPHY_SHOULD_USE_MOCKS") == "true":
    from tests import mocks

    mocks.mock_run_blast()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--query", required=True, help="path to the input peptide FASTA file.")
    parser.add_argument(
        "--out",
        required=True,
        help="path to the blastresults.tsv file generated by blastp.",
    )
    parser.add_argument(
        "--outfmt",
        default=constants.BLAST_OUTFMT,
        help="query format string.",
    )
    parser.add_argument(
        "--max_target_seqs",
        type=int,
        required=True,
        help="maximum number of hits to return.",
    )
    parser.add_argument(
        "--word_size",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--word_size_backoff",
        type=int,
        required=True,
        help="word size to which to back off if the initial call to blastp fails.",
    )
    parser.add_argument(
        "--num_attempts",
        type=int,
        required=True,
        help="The number of times to try calling blastp before exiting with an error.",
    )
    parser.add_argument(
        "--evalue",
        type=float,
        required=True,
    )
    return parser.parse_args()


def _soft_fail_enabled() -> bool:
    return os.environ.get("PC_BLAST_SOFT_FAIL", "0").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def _write_empty_results(path: str) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("")


def main():
    args = parse_args()

    num_tries = 0
    max_num_tries = args.num_attempts
    # Optional hard cap so a hanging NCBI call does not burn num_attempts × timeout.
    cap = os.environ.get("PC_BLAST_MAX_ATTEMPTS", "").strip()
    if cap.isdigit() and int(cap) > 0:
        max_num_tries = min(max_num_tries, int(cap))
    result = None
    while num_tries < max_num_tries:
        word_size = args.word_size if num_tries == 0 else args.word_size_backoff

        print(
            f"[blast] Attempt {num_tries + 1}/{max_num_tries} to call blastp "
            f"(using word size of {word_size})",
            flush=True,
        )
        result = blast_utils.run_blast(
            query=args.query,
            out=args.out,
            max_target_seqs=args.max_target_seqs,
            outfmt=args.outfmt,
            word_size=word_size,
            evalue=args.evalue,
        )
        if result is None:
            result = blast_utils.BlastResult(
                returncode=1,
                stdout=b"",
                stderr=b"[blast] run_blast returned None\n",
            )
        if result.returncode == 0 and Path(args.out).exists() and Path(args.out).stat().st_size > 0:
            sys.exit(0)
        if result.returncode == 0 and Path(args.out).exists():
            # Successful call but zero hits — still a valid empty TSV for extract.
            print("[blast] blastp returned no hits (empty results file)", flush=True)
            sys.exit(0)
        num_tries += 1
        err = ""
        if result is not None and result.stderr:
            err = result.stderr.decode("utf-8", errors="replace")[-300:]
        print(f"[blast] attempt failed rc={getattr(result, 'returncode', '?')}: {err}", flush=True)

    if _soft_fail_enabled():
        _write_empty_results(args.out)
        print(
            f"[blast] SOFT FAIL after {max_num_tries} tries — writing empty {args.out} "
            f"and continuing (Foldseek hits still drive the map). "
            f"Last error: {getattr(result, 'stderr', b'')[-200:]!r}",
            flush=True,
        )
        sys.exit(0)

    sys.exit(
        f"BLAST failed after {max_num_tries} tries. "
        f"The last error message was: {getattr(result, 'stderr', b'')}"
    )


if __name__ == "__main__":
    main()
