mode: "search"
analysis_name: "actin-demo-small"
input_dir: "demo/search-mode/input/"
output_dir: "demo/search-mode/output/"

max_blast_hits: 10
max_foldseek_hits: 10
max_structures: 10

plotting_modes:
- "pca_umap"
