name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # TODO (KC): these pinned deps are copied from the dev env (cartograpy_dev.yml)
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit==3.5.0 ruff==0.1.6 snakefmt==0.8.5

      - name: Run Ruff
        run: ruff check --output-format=github .

      - name: Run Ruff formatter
        run: ruff format --check .

      - name: Run Snakefmt
        run: snakefmt --check .
