name: open-public-sync-pr

on:
  # allow this workflow to be run manually from the Actions tab in the private repo
  workflow_dispatch:

env:
  PUBLIC_REPO_URL: https://github.com/Arcadia-Science/ProteinCartography
  PUBLIC_REPO_REMOTE: public
  # the name of the branch to use for syncing the private repo with the public repo
  SYNC_BRANCH: sync-from-public

jobs:
    open-public-sync-pr:
      runs-on: ubuntu-latest
      # only run this job in the private repo
      if: github.repository == 'Arcadia-Science/ProteinCartography-private'
      steps:
        - name: Checkout the repo
          uses: actions/checkout@v4
          with:
            # this token should be a fine-grained PAT with write permissions
            # for repository contents, pull-requests, and workflows
            # note: a PAT is needed to allow the action to push the sync branch to the private repo;
            # it is not sufficient to grant `permissions: write-all` to the default GITHUB_TOKEN
            # (see https://github.com/orgs/community/discussions/35410)
            token: ${{ secrets.OPEN_PUBLIC_SYNC_PR_PAT }}

            # fetch the full history so that we can check for new commits
            fetch-depth: 0

        - name: Add and fetch the public repo
          run: |
            git remote add ${{ env.PUBLIC_REPO_REMOTE }} ${{ env.PUBLIC_REPO_URL }}
            git fetch --all

        - name: Check for new commits and exit if there are none
          run: |
            NEW_COMMITS=$(git log --oneline --no-merges origin/main..${{ env.PUBLIC_REPO_REMOTE }}/main)
            if [ -z "$NEW_COMMITS" ]; then
                echo "There are no new commits in the public repo; no PR will be opened."
                exit 1
            fi

        - name: Delete the sync branch if it exists
          run: |
            # TODO (KC): if the sync branch already exists, should we check if there is already
            # an open PR associated with it? (this will happen if the action is run twice in a row)
            # if we don't, and there is an open PR, deleting the branch will automatically close it
            git branch -D ${{ env.SYNC_BRANCH }} || true
            git push --force origin --delete ${{ env.SYNC_BRANCH }} || true

        - name: Create and push the sync branch
          run: |
            git branch ${{ env.SYNC_BRANCH }} ${{ env.PUBLIC_REPO_REMOTE }}/main
            git branch --unset-upstream ${{ env.SYNC_BRANCH }}
            git push origin ${{ env.SYNC_BRANCH }}

        - name: Open a PR
          env:
            GH_TOKEN: ${{ secrets.OPEN_PUBLIC_SYNC_PR_PAT }}
            PR_BODY: >
                This PR adds new contributions made to the public repo
                in order to keep the private repo up to date with the public repo.

                It was automatically generated by the
                [open-public-sync-pr](./.github/workflows/open-public-sync-pr.yml)
                GitHub Actions workflow.
          run: |
            gh pr create \
              --repo "${{ github.repository }}" \
              --base main \
              --head "${{ env.SYNC_BRANCH }}" \
              --title "Sync with the public repo" \
              --body "${{ env.PR_BODY }}"
