name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # The 'synchronize' event means the PR was updated with new commits.
    types: [opened, reopened, labeled, synchronize]
  
  # Allow manual triggering.
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: envs/cartography_test.yml
          environment-name: test-env
          cache-environment: true
          cache-downloads: true
          init-shell: bash

      - name: Cache snakemake conda envs
        uses: actions/cache@v4
        id: cache-snakemake-conda-envs
        with:
          path: .snakemake/conda
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ hashFiles('envs/*.yml') }}
          restore-keys: snakemake-conda-${{ runner.os }}--${{ runner.arch }}--

      - name: Create the snakemake conda envs
        if: steps.cache-snakemake-conda-envs.outputs.cache-hit != 'true'
        run: |
          rm -rf .snakemake/conda
          snakemake \
            --configfile demo/search-mode/config_actin.yml \
            --use-conda \
            --conda-frontend mamba \
            --conda-create-envs-only \
            --cores 1

      - name: Run the tests
        run: make test

      - name: Run the tests without mocks
        if: contains(github.event.pull_request.labels.*.name, 'run-slow-tests')
        run: make test-without-mocks
